# Generated by Django 4.1 on 2022-08-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="footfall_bcourt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("footfall_data_bcourt", models.IntegerField(default=0)),
                ("rec_dt_bcourt", models.DateTimeField()),
                ("day_name_bcourt", models.CharField(default="NULL", max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="footfall_DC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("footfall_data_dc", models.IntegerField(default=0)),
                ("rec_dt_dc", models.DateTimeField()),
                ("day_name_dc", models.CharField(default="NULL", max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="footfall_FC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("footfall_data_fc", models.IntegerField(default=0)),
                ("rec_dt_fc", models.DateTimeField()),
                ("day_name_fc", models.CharField(default="NULL", max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="footfall_foodys",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("footfall_data_foodys", models.IntegerField(default=0)),
                ("rec_dt_foodys", models.DateTimeField()),
                ("day_name_foodys", models.CharField(default="NULL", max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="footfall_library",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("footfall_data_library", models.IntegerField(default=0)),
                ("rec_dt_library", models.DateTimeField()),
                ("day_name_library", models.CharField(default="NULL", max_length=200)),
            ],
        ),
    ]
